service: ryansfirstsls
frameworkVersion: "2"
custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModels: true
provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "*"
      Resource: "*"
functions:
  addFood: #the name that aws will save this as for our own future reference
    handler: myMainFile.addFood #defines where the location is file.method
    events: #they list of different types of events to access this method
      - http: #REST (GET/POST/PUT/DELETE) requests will be able to access this
          path: /addfood #the path on the urlbase so its http://baseurl.com/path
          method: post # the type of REST request to access GET/POST/PUT/DELETE
          cors: true # this allows all websites to access it, removing all restrictions
  getMovie:
    handler: myMainFile.getMovie
    events:
      - http:
          path: /getmovie
          method: get
          cors: true
  signUp:
    handler: myMainFile.signUp
    events:
      - http:
          path: /signup
          method: post
          cors: true
  signIn:
    handler: myMainFile.signIn
    events:
      - http:
          path: /signin
          method: post
          cors: true
# REST NOTES
# GET - Yyou cannot add data to the body, only params in the url, this is made for getting an item from the DB
# POST - You generally don't add params to the url, you pass them in the body, this is typically for creaating items in the DB
plugins:
  - serverless-webpack
  - serverless-offline
