service: ryansfirstsls
frameworkVersion: "2"
custom:
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModels: true
provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "*"
      Resource: "*"
functions:
  hello: #the name that aws will save this as for our own future reference
    handler: myMainFile.hello #defines where the location is file.method
    events: #they list of different types of events to access this method
      - http: #REST requests will be able to access this
          path: /hello
          method: get # the type of REST request to access GET/POST/PUT/DELETE
          cors: true # this allows all websites to access it, removing all restrictions
  employee:
    handler: myMainFile.getEmployee
    events:
      - http:
          path: /employee
          method: get
          cors: true
  createMovie:
    handler: myMainFile.createMovie
    events:
      - http:
          path: /createmovie
          method: post
          cors: true
  getMovie:
    handler: myMainFile.getMovie
    events:
      - http:
          path: /getmovie
          method: get
          cors: true
# REST NOTES
# GET - Yyou cannot add data to the body, only params in the url, this is made for getting an item from the DB
# POST - You generally don't add params to the url, you pass them in the body, this is typically for creaating items in the DB
plugins:
  - serverless-webpack
  - serverless-offline
